# 21/20 - 01 - 21 
examen.out: examen1.o modulo1.o
	gcc -o examen.out examen1.o modulo1.o

examen1.o: examen1.c
	gcc -g -c examen1.c

modulo1.o: modulo1.c
	gcc -g -c modulo1.c

clean:
	rm *.o
	clear

compile:
	./final.out
