# 21/20 - 01 - 21 
final.out: Modulo1.o Modulo2.o 
	gcc -o final.out Modulo1.o Modulo2.o

modulo1.o: Modulo1.c
	gcc -g -c Modulo1.c

modulo2.o: Modulo2.c
	gcc -g -c Modulo2.c

clean:
	rm *.o
	clear

compile:
	./final.out
